### ISSUE TITLE
Remove Environ to stick with decouple for all environment variable management

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#51]
is this another dependency? probably redundant, you can keep using decouple -> config

_Originally posted by @bbelderbos in https://github.com/JAWD-001/peer_mentoring/pull/46#discussion_r1199053861_

**Comment by JAWD-001** [comment]
Done

**Comment by bbelderbos** [comment]
Where? I still see this:

<img width="888" alt="image" src="https://github.com/JAWD-001/peer_mentoring/assets/387927/14b964bc-7c93-49de-9db8-66741d7ca686">


!= decouple

**Comment by JAWD-001** [comment]
so, just config() all of that? even 171-179?
